# Generated by Django 5.2.6 on 2025-09-10 06:21

import apps.accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
                ('admin_objects', apps.accounts.models.AdminRoleManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=apps.accounts.models.TextChoiceField(choices=[('B', 'Base'), ('DB', 'Dashboard'), ('UM', 'User Management'), ('CORE', 'Core'), ('CMS', 'CMS'), ('R', 'Reports')], default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='module',
            name='roles',
            field=models.ManyToManyField(related_name='modules', through='accounts.RoleModule', through_fields=('module', 'role'), to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=apps.accounts.models.TextChoiceField(choices=[('L', 'Locked'), ('U', 'Unlocked')], default='U', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=apps.accounts.models.TextChoiceField(choices=[('A', 'Admin'), ('G', 'Guest'), ('N', 'None')], default='N', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
