# Generated by Django 5.2.6 on 2025-09-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_user_managers_alter_module_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
