# Generated by Django 3.2.18 on 2026-01-27 05:13

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_birthdate_user_employee_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='category',
            field=apps.accounts.models.TextChoiceField(choices=[('B', 'Base'), ('DB', 'Dashboard'), ('UM', 'User Management'), ('API', 'API Tester'), ('CORE', 'Core'), ('AUTO', 'Automation'), ('CMS', 'CMS'), ('R', 'Reports')], default='B', max_length=5),
        ),
        migrations.CreateModel(
            name='UserAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', apps.accounts.models.TextChoiceField(choices=[('auth_login', 'Authentication - Login'), ('auth_logout', 'Authentication - Logout'), ('user_create', 'User Accounts - Create User Account'), ('user_update', 'User Accounts - Update User Account'), ('user_delete', 'User Accounts - Delete User Account'), ('role_create', 'Role - Create Role'), ('role_update', 'Role - Update Role'), ('role_delete', 'Role - Delete Role')], max_length=40)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime', '-id'],
            },
        ),
    ]
