# Generated by Django 3.2.18 on 2026-01-27 06:20

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20260127_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudittrail',
            name='action',
            field=apps.accounts.models.TextChoiceField(choices=[('auth_login', 'Authentication - Login'), ('auth_logout', 'Authentication - Logout'), ('user_create', 'User Accounts - Create User Account'), ('user_update', 'User Accounts - Update User Account'), ('user_delete', 'User Accounts - Delete User Account'), ('role_create', 'Role - Create Role'), ('role_update', 'Role - Update Role'), ('role_delete', 'Role - Delete Role'), ('project_create', 'Project - Create Project'), ('project_update', 'Project - Update Project'), ('module_create', 'Modules - Create Modules'), ('module_update', 'Modules - Update Modules'), ('module_delete', 'Modules - Delete Modules'), ('module_scenario_create', 'Modules - Create Scenario from Modules'), ('module_scenario_update', 'Modules - Update Scenario From Modules'), ('module_scenario_delete', 'Modules - Delete Scenario From Modules'), ('scenario_create', 'Scenarios - Create Scenarios'), ('scenario_update', 'Scenarios - Update Scenarios'), ('scenario_delete', 'Scenarios - Delete Scenarios'), ('testcase_create', 'Test Case - Create Test Case'), ('testcase_update', 'Test Case - Update Test Case'), ('testcase_run', 'Test Case - Run Test Case'), ('testcase_delete', 'Test Case - Delete Test Case')], max_length=40),
        ),
    ]
