# Generated by Django 3.2.18 on 2026-01-27 12:46

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_two_factor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudittrail',
            name='action',
            field=apps.accounts.models.TextChoiceField(choices=[('auth_login', 'Authentication - Login'), ('auth_logout', 'Authentication - Logout'), ('user_create', 'User Accounts - Create User Account'), ('user_update', 'User Accounts - Update User Account'), ('user_delete', 'User Accounts - Delete User Account'), ('role_create', 'Role - Create Role'), ('role_update', 'Role - Update Role'), ('role_delete', 'Role - Delete Role'), ('project_create', 'Project - Create Project'), ('project_update', 'Project - Update Project'), ('project_run', 'Projects - Run Automation on Projects'), ('module_run', 'Projects - Run Automation on Modules'), ('scenario_run', 'Projects - Run Automation on Scenarios'), ('testcase_run_automation', 'Projects - Run Automation on Test Cases'), ('module_create', 'Modules - Create Modules'), ('module_update', 'Modules - Update Modules'), ('module_delete', 'Modules - Delete Modules'), ('module_scenario_create', 'Modules - Create Scenario from Modules'), ('module_scenario_update', 'Modules - Update Scenario From Modules'), ('module_scenario_delete', 'Modules - Delete Scenario From Modules'), ('scenario_create', 'Scenarios - Create Scenarios'), ('scenario_update', 'Scenarios - Update Scenarios'), ('scenario_delete', 'Scenarios - Delete Scenarios'), ('testcase_create', 'Test Case - Create Test Case'), ('testcase_update', 'Test Case - Update Test Case'), ('testcase_run', 'Test Case - Run Test Case'), ('testcase_delete', 'Test Case - Delete Test Case'), ('report_export_automated', 'Reports - Export Automated Report'), ('report_export_testcase', 'Reports - Export Test Case Report'), ('environment_create', 'API Environment - Create Environment'), ('environment_update', 'API Environment - Update Environment'), ('environment_delete', 'API Environment - Delete Environment')], max_length=40),
        ),
    ]
