version: '3.8'

volumes:
  db-volume:
  broker-volume:
  redis-volume:
  mediafiles_data:

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data

  broker:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 8080:15672
    volumes:
      - ./infrastructure/broker/local.conf:/etc/rabbitmq/conf.d/local.conf
      - broker-volume:/var/lib/rabbitmq/

  base:
    build: .
    image: automation
    command: echo 0
    volumes:
      - ./:/app

  worker:
    extends:
      service: base
    command: ["runworker"]
    depends_on:
      - db
      - redis
      - broker

  beat:
    extends:
      service: base
    command: ["runbeat"]
    depends_on:
      - db
      - redis
      - broker

  automation:
    extends:
      service: base
    command: ["runprod"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - broker