# Generated by Django 5.2.7 on 2025-10-09 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('default_headers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(default='', max_length=180, unique=True)),
                ('environments', models.ManyToManyField(blank=True, related_name='collections', to='core.apienvironment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('timeout_ms', models.PositiveIntegerField(default=30000)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('body_type', models.CharField(choices=[('none', 'None'), ('json', 'JSON'), ('form', 'Form'), ('raw', 'Raw')], default='none', max_length=10)),
                ('body_json', models.JSONField(blank=True, default=dict)),
                ('body_form', models.JSONField(blank=True, default=dict)),
                ('body_raw', models.TextField(blank=True)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token')], default='none', max_length=10)),
                ('auth_basic', models.JSONField(blank=True, default=dict)),
                ('auth_bearer', models.CharField(blank=True, max_length=512)),
                ('pre_request_script', models.TextField(blank=True)),
                ('tests_script', models.TextField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.apicollection')),
            ],
            options={
                'ordering': ['collection', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApiAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('status_code', 'Status Code'), ('json_path', 'JSON Path'), ('header', 'Header'), ('body_contains', 'Body Contains')], max_length=20)),
                ('field', models.CharField(blank=True, max_length=255)),
                ('expected_value', models.CharField(blank=True, max_length=1024)),
                ('comparator', models.CharField(default='equals', max_length=50)),
                ('allow_partial', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='core.apirequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.apicollection')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.apienvironment')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], max_length=10)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('assertions_passed', models.JSONField(blank=True, default=list)),
                ('assertions_failed', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.apirequest')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.apirun')),
            ],
            options={
                'ordering': ['run', 'order', 'id'],
            },
        ),
    ]
