# Generated by hand for STLC models on 2025-10-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_collection_directories"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("objective", models.TextField()),
                ("modules_under_test", models.JSONField(blank=True, default=list)),
                ("testing_types", models.JSONField(blank=True, default=dict)),
                ("tools", models.JSONField(blank=True, default=list)),
                ("testing_timeline", models.JSONField(blank=True, default=dict)),
                ("testers", models.JSONField(blank=True, default=list)),
                ("approver", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="TestPlanMaintenance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=50)),
                ("summary", models.TextField()),
                ("updates", models.JSONField(blank=True, default=dict)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255)),
                ("approved_by", models.CharField(blank=True, max_length=255)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="core.testplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-created_at", "id"],
                "unique_together": {("plan", "version")},
            },
        ),
        migrations.CreateModel(
            name="TestScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("preconditions", models.TextField(blank=True)),
                ("postconditions", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="core.testplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "title", "id"],
                "unique_together": {("plan", "title")},
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("steps", models.JSONField(blank=True, default=list)),
                ("expected_results", models.JSONField(blank=True, default=list)),
                ("dynamic_variables", models.JSONField(blank=True, default=dict)),
                ("priority", models.CharField(blank=True, max_length=20)),
                ("owner", models.CharField(blank=True, max_length=255)),
                (
                    "related_api_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_cases",
                        to="core.apirequest",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="core.testscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "title", "id"],
                "unique_together": {("scenario", "title")},
            },
        ),
    ]
