# Generated by Django 3.2.18 on 2025-10-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collection_directories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirun',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='runs', to='core.apicollection'),
        ),
    ]
