# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_stlc_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
