# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_testplan_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="objectives",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
