# Generated by Django 3.2.18 on 2025-10-16 02:02

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_testplan_risk_mitigations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('tester', 'Tester'), ('manager', 'Manager')], max_length=20)),
            ],
            options={
                'ordering': ['role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestDataAndAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('in_scope', 'In Scope'), ('out_scope', 'Out of Scope')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['account_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['scenario', 'testcase_id', 'id']},
        ),
        migrations.AddField(
            model_name='testcase',
            name='precondition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(default=uuid.uuid4, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('scenario', 'testcase_id')},
        ),
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50)),
                ('description_of_change', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_histories_approved', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_histories_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('goal', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_entries', to='core.testplan')),
            ],
            options={
                'ordering': ['plan', 'title', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='dynamic_variables',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='title',
        ),
    ]
