# Generated by Django 3.2.18 on 2025-10-16 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20251016_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='test_environment',
            field=models.CharField(blank=True, choices=[('T', 'Test Environment'), ('PS', 'Pre Staging Environment'), ('S', 'Staging Environment'), ('UAT', 'UAT Environment'), ('P', 'Production Environment')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_tools',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plans', to='core.testtools'),
        ),
    ]
