# Generated by Django 4.2 on 2025-10-16 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20251016_0214"),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequest",
            name="body_transforms",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
