# Generated by GitHub Copilot on 2025-10-17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_apirequest_body_transforms"),
    ]

    operations = [
        migrations.AddField(  # persist the raw body format selection per request
            model_name="apirequest",
            name="body_raw_type",
            field=models.CharField(default="text", max_length=20),
        ),
    ]
