# Generated by Django 3.2.18 on 2025-10-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_plan_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='risk_mitigations',
        ),
        migrations.AlterField(
            model_name='riskandmitigationplan',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='risk_mitigation_links', to='core.testplan'),
            preserve_default=False,
        ),
    ]
