# Generated by Django 3.2.18 on 2025-10-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20251020_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodules',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_modules', to='core.testplan'),
        ),
    ]
