# Generated by Django 3.2.18 on 2025-10-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_testmodules_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenario',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='core.testmodules'),
        ),
    ]
