# Generated by Django 3.2.18 on 2025-10-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_testscenario_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
