# Generated by Django 3.2.18 on 2025-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_testcase_testcase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='dynamic_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testcase',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testcase',
            name='priority',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='testcase',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testcase',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
