# Generated by Django 3.2.18 on 2025-10-21 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_auto_20251021_0529'),
    ]

    operations = [
        # 1) Add a temporary FK field (owner_user) nullable so we can populate it
        migrations.AddField(
            model_name='testcase',
            name='owner_user',
            field=models.ForeignKey(
                related_name='test_cases_temp',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # 2) Populate owner_user_id from existing owner text where it's numeric
        migrations.RunSQL(
            sql="""
                UPDATE core_testcase
                SET owner_user_id = (CASE WHEN owner ~ '^[0-9]+$' THEN owner::bigint ELSE NULL END)
                WHERE owner IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 3) Remove the old text owner column
        migrations.RemoveField(
            model_name='testcase',
            name='owner',
        ),
        # 4) Rename owner_user -> owner so the final model matches the code
        migrations.RenameField(
            model_name='testcase',
            old_name='owner_user',
            new_name='owner',
        ),
    ]
