# Generated by Django 3.2.18 on 2025-10-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_testcase_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_case_dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='core.testcase'),
        ),
    ]
