# Generated by Django 3.2.18 on 2025-11-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_testcase_test_case_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='requires_dependency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='dependency_response_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
