# Generated by Django 3.2.18 on 2025-11-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_testcase_dependency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_response_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
