# Generated by Django 3.2.18 on 2025-11-13 04:07

from django.db import migrations, models
import django.db.models.deletion


def populate_projects(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    TestPlan = apps.get_model('core', 'TestPlan')
    TestModules = apps.get_model('core', 'TestModules')
    TestScenario = apps.get_model('core', 'TestScenario')

    existing_names = set(Project.objects.values_list('name', flat=True))

    def unique_name(base: str) -> str:
        base_clean = (base or '').strip() or 'Legacy Project'
        if base_clean not in existing_names:
            existing_names.add(base_clean)
            return base_clean
        suffix = 1
        while True:
            candidate = f"{base_clean} ({suffix})"
            if candidate not in existing_names:
                existing_names.add(candidate)
                return candidate
            suffix += 1

    plan_to_project = {}
    for plan in TestPlan.objects.all():
        project = Project.objects.create(name=unique_name(plan.name or f"Legacy Plan {plan.pk}"))
        plan_to_project[plan.pk] = project

    module_project_map = {}
    for module in TestModules.objects.all():
        plan_fk = getattr(module, 'plan_id', None)
        project = plan_to_project.get(plan_fk)
        if project:
            module.project_id = project.pk
            module.save(update_fields=['project'])
            module_project_map[module.pk] = project

    default_project = None
    for scenario in TestScenario.objects.all():
        plan_fk = getattr(scenario, 'plan_id', None)
        project = plan_to_project.get(plan_fk)
        if not project and scenario.module_id:
            project = module_project_map.get(scenario.module_id)
        if not project:
            if default_project is None:
                default_project = Project.objects.create(name=unique_name('Legacy Project'))
            project = default_project
        scenario.project_id = project.pk
        scenario.save(update_fields=['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_testcase_response_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='riskandmitigationplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='riskandmitigationplan',
            name='mitigation_plan',
        ),
        migrations.RemoveField(
            model_name='riskandmitigationplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='riskandmitigationplan',
            name='risk',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TestDataAndAccounts',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='test_tools',
        ),
        migrations.AlterUniqueTogether(
            name='testplanmaintenance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testplanmaintenance',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testplanobjectives',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testplanscope',
            name='plan',
        ),
        migrations.DeleteModel(
            name='TestStrategy',
        ),
        migrations.RemoveField(
            model_name='versionhistory',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='versionhistory',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='testscenario',
            options={'ordering': ['project', 'title', 'id']},
        ),
        migrations.DeleteModel(
            name='MitigationPlan',
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
        migrations.DeleteModel(
            name='RiskAndMitigationPlan',
        ),
        migrations.DeleteModel(
            name='TestPlanMaintenance',
        ),
        migrations.DeleteModel(
            name='TestPlanObjectives',
        ),
        migrations.DeleteModel(
            name='TestPlanScope',
        ),
        migrations.DeleteModel(
            name='TestTools',
        ),
        migrations.DeleteModel(
            name='VersionHistory',
        ),
        migrations.AddField(
            model_name='testmodules',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_modules', to='core.project'),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.project'),
        ),
        migrations.RunPython(populate_projects, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='testscenario',
            unique_together={('project', 'title')},
        ),
        migrations.RemoveField(
            model_name='testscenario',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='testmodules',
            name='plan',
        ),
        migrations.DeleteModel(
            name='TestPlan',
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='core.project'),
        ),
    ]
