# Generated by Django 3.2.18 on 2025-11-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_apirunresultreport_testcase_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirunresultreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
