# Generated by Django 3.2.18 on 2026-01-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_scenariocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.scenariocomment'),
        ),
    ]
