# Generated by Django 3.2.18 on 2026-01-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_commentreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testscenario',
            name='postconditions',
        ),
        migrations.RemoveField(
            model_name='testscenario',
            name='preconditions',
        ),
        migrations.RemoveField(
            model_name='testscenario',
            name='tags',
        ),
    ]
