# Generated by Django 3.2.18 on 2026-01-27 12:46

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rename_modified_at_to_updated_at_scenariocommentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocommentattachment',
            name='file',
            field=models.FileField(upload_to=apps.core.models.scenario_comment_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='testcaseattachment',
            name='file',
            field=models.FileField(upload_to=apps.core.models.testcase_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='testscenarioattachment',
            name='file',
            field=models.FileField(upload_to=apps.core.models.testscenario_attachment_upload_path),
        ),
    ]
