# Generated by Django 3.2.18 on 2026-02-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_auto_20260127_1246"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoadTestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("module", "Module"),
                            ("scenario", "Scenario"),
                            ("testcase", "Test Case"),
                        ],
                        default="testcase",
                        max_length=20,
                    ),
                ),
                ("selection", models.JSONField(blank=True, default=dict)),
                ("users", models.PositiveIntegerField(default=1)),
                ("ramp_up_seconds", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=60)),
                ("spawn_rate", models.FloatField(default=1.0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("locust_pid", models.IntegerField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("knox_token_key", models.CharField(blank=True, max_length=64)),
                ("workdir", models.CharField(blank=True, max_length=500)),
                ("report_html_relpath", models.CharField(blank=True, max_length=500)),
                ("csv_prefix_relpath", models.CharField(blank=True, max_length=500)),
                ("log_relpath", models.CharField(blank=True, max_length=500)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_test_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_test_runs",
                        to="core.apienvironment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
