# Generated by Django 3.2.18 on 2026-02-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_loadtestrun"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loadtestrun",
            name="environment",
        ),
    ]
