# Generated by Django 3.2.18 on 2026-02-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_loadtestrun_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadtestrun',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('finished', 'Finished'), ('stopped', 'Stopped'), ('failed', 'Failed'), ('error', 'Error')], default='created', max_length=20),
        ),
        migrations.CreateModel(
            name='UITestingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('steps', models.JSONField(blank=True, default=list, help_text='List of UI testing steps with flowchart data')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_testing_records', to='core.testmodules')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_testing_records', to='core.project')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_testing_records', to='core.testscenario')),
            ],
            options={
                'verbose_name': 'UI Testing Record',
                'verbose_name_plural': 'UI Testing Records',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
